### ISSUE TITLE
Missing tagging support in v4.2.0

### ISSUE THREAD

**Issue by tkrafael** [justeattakeaway/JustEat.StatsD#357]
Hi guys,
Don't know if it is an issue, but the v4.2.0 version does not contains the same codebase as main branch.
I was unable to find the nuget package containing tagging support. 
Is this supposed to happen?

**Comment by tkrafael** [comment]
What's pending to allow release of v5 version? Can I help something?

**Comment by martincostello** [comment]
The main sticking point on this is that the breaking changes require various updates internally at Just Eat to prepare for them, and then to validate everything is working as expected end-to-end in some deployed applications in one of our staging environments prior to publishing the `5.0.0` package.

Realistically, that isn't going to start until at least January 2022 due to the imminent holiday period. Version 5.0.0 hasn't been a high enough priority for us to deal with before now unfortunately.

If I get the time this week I'll look into publishing a prerelease package to NuGet.org, but that won't be much different to using a package directly from our CI and using that via a local package reference or adding it to a private NuGet feed you may already have.

**Comment by tkrafael** [comment]
@martincostello by using a nuget package instead of git submodule, make it easier for developers to keep application builds, avoiding inherent complexity of git submodule.
BTW, master version should be in production with our application after holidays. We're getting about 600k transactions/day, whose will create 2.4 milion metrics in AWS Timestream database. We'll rollout slowly, making sure our metrics are ok and publish the results in this repo. I would like to thank you and all amazing commiters of this repo!
