### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rguptar** [justeattakeaway/JustEat.StatsD#414]
@martincostello  The last release was in November 2020. Are there plans to create a new release?

**Comment by martincostello** [comment]
It's quite a low priority item at the moment. The latest changes were breaking and not something we specifically needed internally, and it's quite a big change to upgrade things to the latest version due to dependencies of dependencies etc.

I'll try and find the time to push up a beta release of v5 some time this week.

**Comment by amanpaha** [comment]
Hi @martincostello,
Any update on the latest v5 release which has tag support? We are looking to tags in our application

**Comment by martincostello** [comment]
I happen to be investigating looking at a 4.3.0 release where tags will be opt-in functionality instead of v5 right now, but there are no concrete timelines for a release at this stage.

You can always use the NuGet packages from our [CI builds](https://github.com/justeat/JustEat.StatsD/actions/runs/2658496107) in the meantime.

**Comment by martincostello** [comment]
Sorry for the incredibly long delay - tagging is now supported in JustEat.StatsD 5.0.0 which was just published to NuGet.org.
